# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Authors.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Authors(object):
    def setupUi(self, Authors):
        Authors.setObjectName("Authors")
        Authors.setWindowModality(QtCore.Qt.ApplicationModal)
        Authors.resize(695, 446)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../resources/icons/FSecurity.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Authors.setWindowIcon(icon)
        Authors.setStyleSheet("QLabel { color: white; }")
        Authors.setModal(True)
        self.webView = QtWebKitWidgets.QWebView(Authors)
        self.webView.setGeometry(QtCore.QRect(0, 0, 701, 451))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.webView.setFont(font)
        self.webView.setStyleSheet("QWebView { background-color: #251313; }\n"
"QLabel { color: white; }\n"
"")
        self.webView.setUrl(QtCore.QUrl("file:///resources/icons/FSecurity.png"))
        self.webView.setObjectName("webView")
        self.label = QtWidgets.QLabel(Authors)
        self.label.setGeometry(QtCore.QRect(30, 20, 101, 17))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel { color: white; }")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Authors)
        self.label_2.setGeometry(QtCore.QRect(10, 50, 151, 17))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Authors)
        self.label_3.setGeometry(QtCore.QRect(10, 70, 151, 17))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Authors)
        self.label_4.setGeometry(QtCore.QRect(10, 90, 191, 17))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Authors)
        self.label_5.setGeometry(QtCore.QRect(10, 110, 151, 17))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Authors)
        self.label_6.setGeometry(QtCore.QRect(10, 130, 201, 17))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Authors)
        self.label_7.setGeometry(QtCore.QRect(270, 10, 171, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("QLabel { color: white; }")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(Authors)
        self.label_8.setGeometry(QtCore.QRect(370, 400, 151, 17))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(Authors)
        self.label_9.setGeometry(QtCore.QRect(520, 400, 151, 17))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setUnderline(True)
        font.setWeight(50)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.line = QtWidgets.QFrame(Authors)
        self.line.setGeometry(QtCore.QRect(10, 40, 118, 3))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(Authors)
        self.line_2.setGeometry(QtCore.QRect(220, 30, 261, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.label_10 = QtWidgets.QLabel(Authors)
        self.label_10.setGeometry(QtCore.QRect(310, 40, 101, 17))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("QLabel { color: white; }")
        self.label_10.setObjectName("label_10")

        self.retranslateUi(Authors)
        QtCore.QMetaObject.connectSlotsByName(Authors)

    def retranslateUi(self, Authors):
        _translate = QtCore.QCoreApplication.translate
        Authors.setWindowTitle(_translate("Authors", "Author\'s"))
        self.label.setText(_translate("Authors", "Author\'s"))
        self.label_2.setText(_translate("Authors", "Alfred Valderrama"))
        self.label_3.setText(_translate("Authors", "Nathan Honor"))
        self.label_4.setText(_translate("Authors", "Jhonel Rodrigues Isorena"))
        self.label_5.setText(_translate("Authors", "Hector Cruz"))
        self.label_6.setText(_translate("Authors", "Judelyn Solera Puertollano"))
        self.label_7.setText(_translate("Authors", "Project Management"))
        self.label_8.setText(_translate("Authors", "To be submitted to: "))
        self.label_9.setText(_translate("Authors", "Ms. Jerahmie Odoy"))
        self.label_10.setText(_translate("Authors", "COMSO19"))

from PyQt5 import QtWebKitWidgets

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Authors = QtWidgets.QDialog()
    ui = Ui_Authors()
    ui.setupUi(Authors)
    Authors.show()
    sys.exit(app.exec_())