# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CVEUpload.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_CVE_Dialog(object):
    def setupUi(self, CVE_Dialog):
        CVE_Dialog.setObjectName("CVE_Dialog")
        CVE_Dialog.resize(626, 454)
        CVE_Dialog.setMinimumSize(QtCore.QSize(626, 454))
        CVE_Dialog.setMaximumSize(QtCore.QSize(626, 454))
        CVE_Dialog.setStyleSheet("QDialog { background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0 rgba(17, 5, 0, 255), stop:0.081448 rgba(66, 46, 24, 255), stop:0.104072 rgba(30, 26, 73, 255), stop:0.41629 rgba(7, 4, 37, 255), stop:0.714932 rgba(126, 14, 81, 255), stop:0.751131 rgba(29, 13, 13, 255), stop:0.886878 rgba(70, 70, 51, 255)); }")
        self.CVE_buttonBox = QtWidgets.QDialogButtonBox(CVE_Dialog)
        self.CVE_buttonBox.setGeometry(QtCore.QRect(260, 410, 341, 32))
        self.CVE_buttonBox.setMaximumSize(QtCore.QSize(626, 16777215))
        self.CVE_buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.CVE_buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.CVE_buttonBox.setObjectName("CVE_buttonBox")
        self.Platform_groupBox = QtWidgets.QGroupBox(CVE_Dialog)
        self.Platform_groupBox.setGeometry(QtCore.QRect(10, 0, 611, 401))
        font = QtGui.QFont()
        font.setFamily("ubuntu-light")
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.Platform_groupBox.setFont(font)
        self.Platform_groupBox.setAutoFillBackground(False)
        self.Platform_groupBox.setStyleSheet("QGroupBox { font-family: ubuntu-light; border: 2px solid gray;  border-radius: 5px; margin-top: 1ex; background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(228, 251, 79, 206), stop:0.4 rgba(244, 252, 255, 241), stop:0.425 rgba(244, 252, 255, 241), stop:0.44 rgba(244, 252, 255, 241), stop:1 rgba(244, 252, 255, 241)); }")
        self.Platform_groupBox.setInputMethodHints(QtCore.Qt.ImhNone)
        self.Platform_groupBox.setFlat(True)
        self.Platform_groupBox.setCheckable(False)
        self.Platform_groupBox.setObjectName("Platform_groupBox")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.Platform_groupBox)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(40, 20, 241, 34))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.CVE_Platform_Label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.CVE_Platform_Label.setFont(font)
        self.CVE_Platform_Label.setObjectName("CVE_Platform_Label")
        self.horizontalLayout.addWidget(self.CVE_Platform_Label)
        self.CVE_Platform_Edit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.CVE_Platform_Edit.setStyleSheet("")
        self.CVE_Platform_Edit.setObjectName("CVE_Platform_Edit")
        self.horizontalLayout.addWidget(self.CVE_Platform_Edit)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.Platform_groupBox)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(330, 20, 251, 34))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.CVE_Platform_Ver_Label = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.CVE_Platform_Ver_Label.setFont(font)
        self.CVE_Platform_Ver_Label.setObjectName("CVE_Platform_Ver_Label")
        self.horizontalLayout_2.addWidget(self.CVE_Platform_Ver_Label)
        self.CVE_Author_Edit = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.CVE_Author_Edit.setStyleSheet("")
        self.CVE_Author_Edit.setObjectName("CVE_Author_Edit")
        self.horizontalLayout_2.addWidget(self.CVE_Author_Edit)
        self.CVE_Description_Label = QtWidgets.QLabel(self.Platform_groupBox)
        self.CVE_Description_Label.setGeometry(QtCore.QRect(230, 170, 101, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.CVE_Description_Label.setFont(font)
        self.CVE_Description_Label.setObjectName("CVE_Description_Label")
        self.CVE_Description_Text = QtWidgets.QTextEdit(self.Platform_groupBox)
        self.CVE_Description_Text.setGeometry(QtCore.QRect(10, 200, 581, 191))
        self.CVE_Description_Text.setObjectName("CVE_Description_Text")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.Platform_groupBox)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(40, 110, 541, 34))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.CVE_Platform_Ver_Label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.CVE_Platform_Ver_Label_2.setFont(font)
        self.CVE_Platform_Ver_Label_2.setObjectName("CVE_Platform_Ver_Label_2")
        self.horizontalLayout_3.addWidget(self.CVE_Platform_Ver_Label_2)
        self.CVE_Document_Edit = QtWidgets.QLineEdit(self.horizontalLayoutWidget_3)
        self.CVE_Document_Edit.setStyleSheet("")
        self.CVE_Document_Edit.setObjectName("CVE_Document_Edit")
        self.horizontalLayout_3.addWidget(self.CVE_Document_Edit)
        self.CVE_pdf = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.CVE_pdf.setObjectName("CVE_pdf")
        self.horizontalLayout_3.addWidget(self.CVE_pdf)
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.Platform_groupBox)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(40, 50, 241, 34))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.CVE_Platform_Version_Label = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.CVE_Platform_Version_Label.setFont(font)
        self.CVE_Platform_Version_Label.setObjectName("CVE_Platform_Version_Label")
        self.horizontalLayout_4.addWidget(self.CVE_Platform_Version_Label)
        self.CVE_Platform_Version_Edit = QtWidgets.QLineEdit(self.horizontalLayoutWidget_4)
        self.CVE_Platform_Version_Edit.setStyleSheet("")
        self.CVE_Platform_Version_Edit.setObjectName("CVE_Platform_Version_Edit")
        self.horizontalLayout_4.addWidget(self.CVE_Platform_Version_Edit)
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(self.Platform_groupBox)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(330, 50, 251, 34))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.CVE_Platform_Ver_Label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget_5)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.CVE_Platform_Ver_Label_3.setFont(font)
        self.CVE_Platform_Ver_Label_3.setObjectName("CVE_Platform_Ver_Label_3")
        self.horizontalLayout_5.addWidget(self.CVE_Platform_Ver_Label_3)
        self.CVE_Title_Edit = QtWidgets.QLineEdit(self.horizontalLayoutWidget_5)
        self.CVE_Title_Edit.setStyleSheet("")
        self.CVE_Title_Edit.setObjectName("CVE_Title_Edit")
        self.horizontalLayout_5.addWidget(self.CVE_Title_Edit)

        self.retranslateUi(CVE_Dialog)
        self.CVE_buttonBox.accepted.connect(CVE_Dialog.accept)
        self.CVE_buttonBox.rejected.connect(CVE_Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(CVE_Dialog)

    def retranslateUi(self, CVE_Dialog):
        _translate = QtCore.QCoreApplication.translate
        CVE_Dialog.setWindowTitle(_translate("CVE_Dialog", "Upload CVE"))
        self.Platform_groupBox.setStatusTip(_translate("CVE_Dialog", "Platform"))
        self.Platform_groupBox.setTitle(_translate("CVE_Dialog", "CVE"))
        self.CVE_Platform_Label.setText(_translate("CVE_Dialog", "CVE Platform:"))
        self.CVE_Platform_Ver_Label.setText(_translate("CVE_Dialog", "CVE Email Author:"))
        self.CVE_Description_Label.setText(_translate("CVE_Dialog", "CVE Description"))
        self.CVE_Platform_Ver_Label_2.setText(_translate("CVE_Dialog", "CVE Documentation:"))
        self.CVE_pdf.setText(_translate("CVE_Dialog", "Documentation"))
        self.CVE_Platform_Version_Label.setText(_translate("CVE_Dialog", "CVE Platform Version:"))
        self.CVE_Platform_Ver_Label_3.setText(_translate("CVE_Dialog", "CVE Title:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CVE_Dialog = QtWidgets.QDialog()
    ui = Ui_CVE_Dialog()
    ui.setupUi(CVE_Dialog)
    CVE_Dialog.show()
    sys.exit(app.exec_())

