# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ExpUpload.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Exp_Dialog(object):
    def setupUi(self, Exp_Dialog):
        Exp_Dialog.setObjectName("Exp_Dialog")
        Exp_Dialog.setWindowModality(QtCore.Qt.ApplicationModal)
        Exp_Dialog.resize(626, 454)
        Exp_Dialog.setMinimumSize(QtCore.QSize(626, 454))
        Exp_Dialog.setMaximumSize(QtCore.QSize(626, 454))
        Exp_Dialog.setStyleSheet("QDialog { background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0 rgba(17, 5, 0, 255), stop:0.081448 rgba(66, 46, 24, 255), stop:0.104072 rgba(30, 26, 73, 255), stop:0.41629 rgba(7, 4, 37, 255), stop:0.714932 rgba(126, 14, 81, 255), stop:0.751131 rgba(29, 13, 13, 255), stop:0.886878 rgba(70, 70, 51, 255)); }")
        Exp_Dialog.setWindowFilePath("")
        Exp_Dialog.setModal(True)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("resources/icons/FSecurity.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Exp_Dialog.setWindowIcon(icon)
        self.ExpButtonBox = QtWidgets.QDialogButtonBox(Exp_Dialog)
        self.ExpButtonBox.setGeometry(QtCore.QRect(420, 400, 191, 32))
        self.ExpButtonBox.setOrientation(QtCore.Qt.Horizontal)
        self.ExpButtonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.ExpButtonBox.setObjectName("ExpButtonBox")
        self.Platform_groupBox = QtWidgets.QGroupBox(Exp_Dialog)
        self.Platform_groupBox.setGeometry(QtCore.QRect(10, 10, 601, 101))
        font = QtGui.QFont()
        font.setFamily("ubuntu-light")
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.Platform_groupBox.setFont(font)
        self.Platform_groupBox.setAutoFillBackground(False)
        self.Platform_groupBox.setStyleSheet("QGroupBox { font-family: ubuntu-light; border: 2px solid gray;  border-radius: 5px; margin-top: 1ex; background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(228, 251, 79, 206), stop:0.4 rgba(244, 252, 255, 241), stop:0.425 rgba(244, 252, 255, 241), stop:0.44 rgba(244, 252, 255, 241), stop:1 rgba(244, 252, 255, 241)); }")
        self.Platform_groupBox.setInputMethodHints(QtCore.Qt.ImhNone)
        self.Platform_groupBox.setFlat(True)
        self.Platform_groupBox.setCheckable(False)
        self.Platform_groupBox.setObjectName("Platform_groupBox")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.Platform_groupBox)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(170, 60, 259, 25))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.verticalLayoutWidget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.Exp_x86_Opt = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.Exp_x86_Opt.setFont(font)
        self.Exp_x86_Opt.setObjectName("Exp_x86_Opt")
        self.horizontalLayout_3.addWidget(self.Exp_x86_Opt)
        self.Exp_x64_Opt = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.Exp_x64_Opt.setFont(font)
        self.Exp_x64_Opt.setObjectName("Exp_x64_Opt")
        self.horizontalLayout_3.addWidget(self.Exp_x64_Opt)
        self.Exp_x86_64_Opt = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.Exp_x86_64_Opt.setFont(font)
        self.Exp_x86_64_Opt.setObjectName("Exp_x86_64_Opt")
        self.horizontalLayout_3.addWidget(self.Exp_x86_64_Opt)
        self.Exp_ALL_Opt = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.Exp_ALL_Opt.setFont(font)
        self.Exp_ALL_Opt.setObjectName("Exp_ALL_Opt")
        self.horizontalLayout_3.addWidget(self.Exp_ALL_Opt)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.Platform_groupBox)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(30, 20, 201, 34))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Exp_Platform_Label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Exp_Platform_Label.setFont(font)
        self.Exp_Platform_Label.setObjectName("Exp_Platform_Label")
        self.horizontalLayout.addWidget(self.Exp_Platform_Label)
        self.Exp_Platform_Edit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.Exp_Platform_Edit.setStyleSheet("")
        self.Exp_Platform_Edit.setObjectName("Exp_Platform_Edit")
        self.horizontalLayout.addWidget(self.Exp_Platform_Edit)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.Platform_groupBox)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(380, 20, 201, 34))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Exp_Platform_Version_Label = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Exp_Platform_Version_Label.setFont(font)
        self.Exp_Platform_Version_Label.setObjectName("Exp_Platform_Version_Label")
        self.horizontalLayout_2.addWidget(self.Exp_Platform_Version_Label)
        self.Exp_Platform_Version_Edit = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.Exp_Platform_Version_Edit.setStyleSheet("")
        self.Exp_Platform_Version_Edit.setObjectName("Exp_Platform_Version_Edit")
        self.horizontalLayout_2.addWidget(self.Exp_Platform_Version_Edit)
        self.Information_groupBox = QtWidgets.QGroupBox(Exp_Dialog)
        self.Information_groupBox.setGeometry(QtCore.QRect(10, 110, 601, 281))
        font = QtGui.QFont()
        font.setFamily("ubuntu-light")
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.Information_groupBox.setFont(font)
        self.Information_groupBox.setStyleSheet("QGroupBox { font-family: ubuntu-light; border: 2px solid gray;  border-radius: 5px; margin-top: 1ex; background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(228, 251, 79, 206), stop:0.4 rgba(244, 252, 255, 241), stop:0.425 rgba(244, 252, 255, 241), stop:0.44 rgba(244, 252, 255, 241), stop:1 rgba(244, 252, 255, 241)); }")
        self.Information_groupBox.setObjectName("Information_groupBox")
        self.Exp_Type = QtWidgets.QComboBox(self.Information_groupBox)
        self.Exp_Type.setGeometry(QtCore.QRect(510, 40, 75, 33))
        self.Exp_Type.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.Exp_Type.setCurrentText("")
        self.Exp_Type.setMaxVisibleItems(3)
        self.Exp_Type.setObjectName("Exp_Type")
        self.Exp_Ratings = QtWidgets.QComboBox(self.Information_groupBox)
        self.Exp_Ratings.setGeometry(QtCore.QRect(510, 110, 75, 33))
        self.Exp_Ratings.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.Exp_Ratings.setCurrentText("")
        self.Exp_Ratings.setMaxVisibleItems(3)
        self.Exp_Ratings.setObjectName("Exp_Ratings")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.Information_groupBox)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(30, 30, 201, 34))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.Exp_Title_Label = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Exp_Title_Label.setFont(font)
        self.Exp_Title_Label.setObjectName("Exp_Title_Label")
        self.horizontalLayout_4.addWidget(self.Exp_Title_Label)
        self.Exp_Title_Edit = QtWidgets.QLineEdit(self.horizontalLayoutWidget_3)
        self.Exp_Title_Edit.setStyleSheet("")
        self.Exp_Title_Edit.setObjectName("Exp_Title_Edit")
        self.horizontalLayout_4.addWidget(self.Exp_Title_Edit)
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.Information_groupBox)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(30, 70, 421, 36))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.Exp_Mod_Label = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Exp_Mod_Label.setFont(font)
        self.Exp_Mod_Label.setObjectName("Exp_Mod_Label")
        self.horizontalLayout_5.addWidget(self.Exp_Mod_Label)
        self.Exp_Mod_Edit = QtWidgets.QLineEdit(self.horizontalLayoutWidget_4)
        self.Exp_Mod_Edit.setStyleSheet("")
        self.Exp_Mod_Edit.setObjectName("Exp_Mod_Edit")
        self.horizontalLayout_5.addWidget(self.Exp_Mod_Edit)
        self.Exp_Mod_Push = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Exp_Mod_Push.setFont(font)
        self.Exp_Mod_Push.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Exp_Mod_Push.setMouseTracking(True)
        self.Exp_Mod_Push.setTabletTracking(True)
        self.Exp_Mod_Push.setAcceptDrops(True)
        self.Exp_Mod_Push.setFlat(False)
        self.Exp_Mod_Push.setObjectName("Exp_Mod_Push")
        self.horizontalLayout_5.addWidget(self.Exp_Mod_Push)
        self.horizontalLayoutWidget_7 = QtWidgets.QWidget(self.Information_groupBox)
        self.horizontalLayoutWidget_7.setGeometry(QtCore.QRect(30, 110, 421, 36))
        self.horizontalLayoutWidget_7.setObjectName("horizontalLayoutWidget_7")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_7)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.Exp_Opt_Label = QtWidgets.QLabel(self.horizontalLayoutWidget_7)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Exp_Opt_Label.setFont(font)
        self.Exp_Opt_Label.setObjectName("Exp_Opt_Label")
        self.horizontalLayout_8.addWidget(self.Exp_Opt_Label)
        self.Exp_Opt_Edit = QtWidgets.QLineEdit(self.horizontalLayoutWidget_7)
        self.Exp_Opt_Edit.setStyleSheet("")
        self.Exp_Opt_Edit.setObjectName("Exp_Opt_Edit")
        self.horizontalLayout_8.addWidget(self.Exp_Opt_Edit)
        self.Exp_Opt_JSON = QtWidgets.QPushButton(self.horizontalLayoutWidget_7)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Exp_Opt_JSON.setFont(font)
        self.Exp_Opt_JSON.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Exp_Opt_JSON.setMouseTracking(True)
        self.Exp_Opt_JSON.setTabletTracking(True)
        self.Exp_Opt_JSON.setAcceptDrops(True)
        self.Exp_Opt_JSON.setFlat(False)
        self.Exp_Opt_JSON.setObjectName("Exp_Opt_JSON")
        self.horizontalLayout_8.addWidget(self.Exp_Opt_JSON)
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(self.Information_groupBox)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(260, 30, 231, 34))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.Exp_Author_Label = QtWidgets.QLabel(self.horizontalLayoutWidget_5)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Exp_Author_Label.setFont(font)
        self.Exp_Author_Label.setObjectName("Exp_Author_Label")
        self.horizontalLayout_6.addWidget(self.Exp_Author_Label)
        self.Exp_Author_Edit = QtWidgets.QLineEdit(self.horizontalLayoutWidget_5)
        self.Exp_Author_Edit.setStyleSheet("")
        self.Exp_Author_Edit.setObjectName("Exp_Author_Edit")
        self.horizontalLayout_6.addWidget(self.Exp_Author_Edit)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.Information_groupBox)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(30, 150, 491, 118))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Exp_Description_Label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Exp_Description_Label.setFont(font)
        self.Exp_Description_Label.setObjectName("Exp_Description_Label")
        self.verticalLayout.addWidget(self.Exp_Description_Label)
        self.Exp_Description_Text = QtWidgets.QTextEdit(self.verticalLayoutWidget_2)
        self.Exp_Description_Text.setObjectName("Exp_Description_Text")
        self.verticalLayout.addWidget(self.Exp_Description_Text)
        self.label = QtWidgets.QLabel(self.Information_groupBox)
        self.label.setGeometry(QtCore.QRect(510, 20, 54, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.Information_groupBox)
        self.label_2.setGeometry(QtCore.QRect(510, 90, 54, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Exp_Dialog)
       # self.ExpButtonBox.accepted.connect(Exp_Dialog.accept)
       # self.ExpButtonBox.rejected.connect(Exp_Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Exp_Dialog)

    def retranslateUi(self, Exp_Dialog):
        _translate = QtCore.QCoreApplication.translate
        Exp_Dialog.setWindowTitle(_translate("Exp_Dialog", "Upload Exploit"))
        Exp_Dialog.setStatusTip(_translate("Exp_Dialog", "Upload Exploit"))
        self.Platform_groupBox.setStatusTip(_translate("Exp_Dialog", "Platform"))
        self.Platform_groupBox.setTitle(_translate("Exp_Dialog", "Platform"))
        self.Exp_x86_Opt.setText(_translate("Exp_Dialog", "x&86"))
        self.Exp_x64_Opt.setText(_translate("Exp_Dialog", "x64"))
        self.Exp_x86_64_Opt.setText(_translate("Exp_Dialog", "x86_64"))
        self.Exp_ALL_Opt.setText(_translate("Exp_Dialog", "ALL"))
        self.Exp_Platform_Label.setText(_translate("Exp_Dialog", "Target platform:"))
        self.Exp_Platform_Version_Label.setText(_translate("Exp_Dialog", "Target Version"))
        self.Information_groupBox.setTitle(_translate("Exp_Dialog", "Information"))
        self.Exp_Title_Label.setText(_translate("Exp_Dialog", "Exploit title: "))
        self.Exp_Mod_Label.setText(_translate("Exp_Dialog", "Exploit Module:"))
        self.Exp_Mod_Push.setStatusTip(_translate("Exp_Dialog", "Exploit Module"))
        self.Exp_Mod_Push.setText(_translate("Exp_Dialog", "Module"))
        self.Exp_Opt_Label.setText(_translate("Exp_Dialog", "Exploit Options:"))
        self.Exp_Opt_JSON.setStatusTip(_translate("Exp_Dialog", "Exploit Module"))
        self.Exp_Opt_JSON.setText(_translate("Exp_Dialog", "JSON"))
        self.Exp_Author_Label.setText(_translate("Exp_Dialog", "Author Email:"))
        self.Exp_Description_Label.setText(_translate("Exp_Dialog", "Exploit Description"))
        self.label.setText(_translate("Exp_Dialog", "Type"))
        self.label_2.setText(_translate("Exp_Dialog", "Ratings"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Exp_Dialog = QtWidgets.QDialog()
    ui = Ui_Exp_Dialog()
    ui.setupUi(Exp_Dialog)
    Exp_Dialog.show()
    sys.exit(app.exec_())

