-- MySQL Script generated by MySQL Workbench
-- Friday, 02 August, 2019 04:54:04 PM PST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema fsecurityframework
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema fsecurityframework
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `fsecurityframework` DEFAULT CHARACTER SET utf8 ;
USE `fsecurityframework` ;

-- -----------------------------------------------------
-- Table `fsecurityframework`.`Exploit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fsecurityframework`.`Exploit` (
  `EXP_ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Title` VARCHAR(100) NOT NULL,
  `Description` VARCHAR(500) NOT NULL DEFAULT 'No Description',
  `Language` VARCHAR(45) NOT NULL DEFAULT 'Unknown',
  `Type` VARCHAR(100) NOT NULL DEFAULT 'Local',
  `Date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `Ratings` VARCHAR(100) NOT NULL DEFAULT 'Low',
  `Exploit_Author` VARCHAR(100) NOT NULL DEFAULT 'Alfred Valderrama',
  PRIMARY KEY (`EXP_ID`),
  UNIQUE INDEX `EXP_ID_UNIQUE` (`EXP_ID` ASC));


-- -----------------------------------------------------
-- Table `fsecurityframework`.`CVE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fsecurityframework`.`CVE` (
  `CVE_ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Title` VARCHAR(45) NOT NULL,
  `Description` LONGTEXT NULL,
  `CVE_Author` VARCHAR(100) NOT NULL DEFAULT 'Alfred Valderrama',
  `Documentation` VARCHAR(300) NULL,
  PRIMARY KEY (`CVE_ID`),
  UNIQUE INDEX `CVE_ID_UNIQUE` (`CVE_ID` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fsecurityframework`.`Malware`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fsecurityframework`.`Malware` (
  `MW_ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Title` VARCHAR(100) NOT NULL,
  `Description` VARCHAR(500) NULL DEFAULT 'No Description',
  `Language` VARCHAR(200) NULL DEFAULT 'Unknown',
  `Type` VARCHAR(100) NULL DEFAULT 'Local',
  `Date` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `Ratings` VARCHAR(100) NULL DEFAULT 'Low',
  `Malware_Author` VARCHAR(100) NULL DEFAULT 'Alfred Valderrama',
  PRIMARY KEY (`MW_ID`),
  UNIQUE INDEX `MW_ID_UNIQUE` (`MW_ID` ASC));


-- -----------------------------------------------------
-- Table `fsecurityframework`.`Platform`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fsecurityframework`.`Platform` (
  `Platform_ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `EXP_ID` INT UNSIGNED NULL DEFAULT NULL,
  `MW_ID` INT UNSIGNED NULL DEFAULT NULL,
  `CVE_ID` INT UNSIGNED NULL DEFAULT NULL,
  `Name` VARCHAR(45) NOT NULL DEFAULT 'Any Platform',
  `Version` VARCHAR(45) NOT NULL DEFAULT 'Any Version',
  `Arch` ENUM('x86', 'x64', 'x86_64', 'ALL') NOT NULL DEFAULT 'ALL',
  PRIMARY KEY (`Platform_ID`),
  UNIQUE INDEX `Platform_ID_UNIQUE` (`Platform_ID` ASC),
  UNIQUE INDEX `EXP_ID_UNIQUE` (`EXP_ID` ASC),
  UNIQUE INDEX `MW_ID_UNIQUE` (`MW_ID` ASC),
  UNIQUE INDEX `CVE_ID_UNIQUE` (`CVE_ID` ASC),
  CONSTRAINT `fk_Platform_Exploit`
    FOREIGN KEY (`EXP_ID`)
    REFERENCES `fsecurityframework`.`Exploit` (`EXP_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Platform_Malware`
    FOREIGN KEY (`MW_ID`)
    REFERENCES `fsecurityframework`.`Malware` (`MW_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Platform_CVE`
    FOREIGN KEY (`CVE_ID`)
    REFERENCES `fsecurityframework`.`CVE` (`CVE_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fsecurityframework`.`Module`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fsecurityframework`.`Module` (
  `MOD_ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `EXP_ID` INT UNSIGNED NULL DEFAULT NULL,
  `MW_ID` INT UNSIGNED NULL DEFAULT NULL,
  `module_name` VARCHAR(500) NOT NULL DEFAULT 'Not Specified',
  PRIMARY KEY (`MOD_ID`),
  UNIQUE INDEX `MOD_ID_UNIQUE` (`MOD_ID` ASC),
  UNIQUE INDEX `EXP_ID_UNIQUE` (`EXP_ID` ASC),
  UNIQUE INDEX `MW_ID_UNIQUE` (`MW_ID` ASC),
  CONSTRAINT `fk_Module_Exploit`
    FOREIGN KEY (`EXP_ID`)
    REFERENCES `fsecurityframework`.`Exploit` (`EXP_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Module_Malware`
    FOREIGN KEY (`MW_ID`)
    REFERENCES `fsecurityframework`.`Malware` (`MW_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fsecurityframework`.`Options`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fsecurityframework`.`Options` (
  `OPT_ID` INT NOT NULL AUTO_INCREMENT,
  `EXP_ID` INT UNSIGNED NULL DEFAULT NULL,
  `MW_ID` INT UNSIGNED NULL DEFAULT NULL,
  `option_name` VARCHAR(500) NULL,
  PRIMARY KEY (`OPT_ID`),
  UNIQUE INDEX `OPT_ID_UNIQUE` (`OPT_ID` ASC),
  UNIQUE INDEX `EXP_ID_UNIQUE` (`EXP_ID` ASC),
  UNIQUE INDEX `MW_ID_UNIQUE` (`MW_ID` ASC),
  CONSTRAINT `fk_Options_Exploit`
    FOREIGN KEY (`EXP_ID`)
    REFERENCES `fsecurityframework`.`Exploit` (`EXP_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Options_Malware`
    FOREIGN KEY (`MW_ID`)
    REFERENCES `fsecurityframework`.`Malware` (`MW_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
